# Generated by Django 5.1.1 on 2024-12-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                ("mobile", models.IntegerField()),
                ("pin", models.IntegerField()),
                ("address", models.CharField(default="", max_length=1000)),
                ("member_installment_limit", models.FloatField(default=0)),
                ("maximum_loan", models.FloatField(default=0)),
                ("loan_interest", models.FloatField(default=0)),
                ("status", models.IntegerField(default=0)),
                ("date", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
