# Generated by Django 5.1.1 on 2024-12-05 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0002_alter_group_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=1000)),
                ("mobile", models.IntegerField()),
                ("pin", models.IntegerField()),
                ("status", models.IntegerField(default=1)),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="group.group",
                    ),
                ),
            ],
        ),
    ]
