# Generated by Django 5.1.1 on 2024-12-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0003_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan_demand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("demand_amount", models.FloatField(null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="group.group",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="group.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member_installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateField(auto_now_add=True)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="group.group",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="group.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member_loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount", models.FloatField()),
                ("minimum_loan_installment", models.FloatField(default=0)),
                ("date", models.DateField(auto_now_add=True)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                ("loan_status", models.IntegerField(default=1)),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="group.group",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="group.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member_loan_installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_amount", models.FloatField()),
                ("interest_amount", models.FloatField(null=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="group.group",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="group.member_loan",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="group.member",
                    ),
                ),
            ],
        ),
    ]
