# Generated by Django 5.1.1 on 2024-12-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_member_sangh_loan_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='loan_bank_interest',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='loan_sangh_interest',
            field=models.FloatField(default=0),
        ),
    ]
