# Generated by Django 5.1.1 on 2024-12-21 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_group_loan_bank_interest_group_loan_sangh_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_sangh_loan_installment',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='group.member_sangh_loan'),
        ),
    ]
