# Generated by Django 5.1.1 on 2024-12-26 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_alter_member_sangh_loan_installment_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Starting_interest_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_amount', models.FloatField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='group.group')),
            ],
        ),
    ]
