# Generated by Django 5.1.1 on 2024-12-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_starting_interest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='starting_total_interest_amount',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Starting_interest_amount',
        ),
    ]
